Doyun
nbcamp/youtube-clone-app pull request #2
Opened 2023-09-07 00:33 UTC by doyuny

2023-09-07 02:20 UTC, jinyongp requested changes

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +        guard let signInView = view as? SignInView else { fatalError("View is not of type SignInView") }
`rootView` 속성을 이용해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +final class SignInViewController: TypedViewController<SignInView>, UITextFieldDelegate {
Delegate는 별도의 extension을 추가해서 작성해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +    }
`TypedViewController`에서 보시면 아시겠지만 이미 loadView에서 `rootView` 인스턴스를 생성하고 `initializeUI`를 호출하고 있어요. 여기서 또 해줄 필요가 없습니다.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +        signInView.signInButton.addTarget(self, action: #selector(handleSigninButtonTapped), for: .touchUpInside)
view를 통해서 내부의 요소에 접근할 수 있으면 안돼요. 버튼을 눌렀을 때 실행할 EventBus를 등록해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +        print("tap")
불필요한 print는 제거해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +        EventBus.shared.on(SignInEvent.self, by: self, handleSignIn)
이게 있는데 왜 addTarget을 또 등록하신건지...

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +    }
이름 붙여야하니까 이렇게 별도 함수 만들지 말고 EventBus.shared.on에 그냥 클로저로 작성해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +    }
여기 말고 Events 파일에 이미 있어요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +final class SignInViewController: TypedViewController<SignInView>, UITextFieldDelegate {
애초에 TextField는 View이기 때문에 여기 있으면 안됩니다...

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignUpViewController.swift
> +class SignUpViewController: TypedViewController<SignUpView>, UITextFieldDelegate {
final 키워드 웬만하면 사용하시는게 좋아요

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Resources/SceneDelegate.swift
이 파일은 수정하시면 안 돼요~

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Services/AuthService.swift
> +    static let shared = AuthService()
```suggestion
final class AuthService {
    static let shared = AuthService()
    private init() {}
```

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Services/AuthService.swift
> +    ]
현재 로그인 중인 사용자가 여러 명이 될 일은 없어요. user 하나로만 관리해도 됩니다. `User` 모델 타입으로요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Services/AuthService.swift
> +    }
```suggestion
    var isAuthenticated: Bool { user != nil } 
```

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Utilities/EventBus.swift
> +}
여기에 추가하시면 안되고 `Events` 파일에 추가해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignInView/SignInView.swift
> +    let imageView: UIImageView = {
`private lazy var` 혹은 `private let`으로 작성해주세요. view 관련 요소가 외부에 노출될 필요가 없습니다. 웬만하면 private lazy로 작성해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignInView/SignInView.swift
> +    var onSignUpButtonTapped: (() -> Void)?
클로저 말고 EventBus를 활용해주세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignInView/SignInView.swift
> +        backgroundColor = .white
.white 말고 .systemBackground를 쓰셔야 dark theme에도 대응이 됩니다.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignInView/SignInView.swift
> +        addSubview(signUpButton)
이렇게 하지 말고 StackView를 활용해보세요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignUpView/SignUpView.swift
> +    private let emailTextField: UITextField = {
`private lazy var`를 사용하시면 여기에서 바로 `textField.delgate = self`를 작성할 수 있어요.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignUpView/SignUpView.swift
> +    }
initializeUI는 `TypedViewController`에서 실행합니다.

2023-09-07 02:20 UTC, jinyongp commented on YoutubeCloneApp/Views/SignUpView/SignUpView.swift
> +    }
이건 필요가 없겠네요.

2023-09-07 03:14 UTC, luttoli approved these changes

2023-09-07 03:15 UTC, jinyongp requested changes

2023-09-07 03:15 UTC, jinyongp commented on YoutubeCloneApp/Services/AuthService.swift
> +    func signUp(email: String, password: String, completion: @escaping (Bool) -> Void) {
모든 사용자 정보를 불러올 수 있도록 해주세요.

```swift
final class User {
    @Publishable var avatar: Base64?
    @Publishable var name: String
    @Publishable var email: String
    var password: String

    init(avatar: Base64? = nil, name: String, email: String, password: String) {
        self.avatar = avatar
        self.name = name
        self.email = email
        self.password = password
    }
}
```

2023-09-08 03:07 UTC, jinyongp requested changes

2023-09-08 03:07 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +                print("signin fail")
alert 띄워서 로그인 실패 알려주기

2023-09-08 03:07 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
> +                listener.navigationController?.pushViewController(homeVC, animated: true)
SignInViewController는 present로 보여주기 때문에 dismiss해야 합니다.

2023-09-08 03:07 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignInViewController.swift
>      }
클래스, 구조체 내의 순서

public이 먼저 private이 나중

1. 속성 목록 (저장(감시자) -> 계산)
2. 생성자 (+ 소멸자)
3. 라이프 사이클 함수 (호출 순서대로)
4. 공개된 함수 (public)
5. 비공개된 함수 (private)

2023-09-08 03:07 UTC, jinyongp commented on YoutubeCloneApp/Controllers/SignUpViewController.swift
> +        rootView.signUpButton.addTarget(self, action: #selector(handleSignUpButtonTapped), for: .touchUpInside)
view 내부의 요소는 접근할 수 없어야 해요. 내부에서 처리해주세요.

2023-09-08 03:07 UTC, jinyongp commented on YoutubeCloneApp/Resources/SceneDelegate.swift
이 파일 변경내역은 없애주세요. :)

2023-09-09 12:01 UTC, merged