Youtube home UI구현
nbcamp/youtube-clone-app pull request #3
Opened 2023-09-07 03:15 UTC by luttoli

![Simulator Screenshot - iPhone 14 Pro - 2023-09-07 at 09 36 15](https://github.com/nbcamp/youtube-clone-app/assets/107012166/2c141cd8-0eef-4f98-b94a-16177e9c65a9)

2023-09-07 04:00 UTC, jinyongp requested changes

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Controllers/Events.swift
> +struct CollectionViewRefresh: EventProtocol {
CollectionViewRefresh 보단 RefreshVideos가 더 나을 거 같네요. TableView에서 사용할 수 있는거니깐요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    static let identifier = "HomeVideoCell"
```suggestion
final class HomeVideoCell: UICollectionViewCell, Identifier {
```

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    lazy var thumbnailImage: UIImageView = {
```suggestion
    private lazy var thumbnailImage: UIImageView = {
```

웬만하면 내부 view를 외부에 노출시키지 않는게 좋아요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    func cellPrint() {
함수의 이름은 주로 동사형이 앞에 오도록 작명해요. `setupCell` 혹은 `initializeCell`이 좋겠네요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +        textBoxStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -10).isActive = true
isActive 매번 붙여주기보다 `NSLayoutConstraint.activate` 쓰는게 더 깔끔해보이네요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +    let refreshControl = UIRefreshControl()
```suggestion
    private let refreshControl = UIRefreshControl()
```

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +    //home화면에 노출될 비디오 리스트 CollectionView
함수 이름으로 설명 가능한 불필요한 주석은 달지 않는게 좋아요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +    //collectionView 속성
https://nesoy.github.io/articles/2018-01/CleanCode-Comment

CleanCode에서 좋은 주석에 대한 내용이 있는데 읽어보셔도 좋습니다.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        }
해당 페이지에서는 사용자 정보 보여줄 일이 없을테니 삭제해도 될거 같네요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
>          }
어차피 UICollectionViewCell()를 반환하면 에러나서 앱 종료되더라구요. 

```suggestion
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "HomeVideoCell", for: indexPath) as! HomeVideoCell
```

이렇게 쓰셔도 될 듯 합니다.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        print(collectionView.bounds.width)
테스트 용으로 추가한 print는 지워주세요.

2023-09-07 04:00 UTC, jinyongp commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        cell.uploadDateLabel.text = dateList[indexPath.row]
차라리 나중에 ViewModel 자체를 전달하게 하는 걸로 변경하는게 좋을 거 같네요.

2023-09-07 06:05 UTC, luttoli commented on YoutubeCloneApp/Controllers/Events.swift
> +struct CollectionViewRefresh: EventProtocol {
확인했습니다.

2023-09-07 06:05 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    static let identifier = "HomeVideoCell"
확인했습니다.

2023-09-07 06:06 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    lazy var thumbnailImage: UIImageView = {
확인했습니다.
@Publishable private(set) var videos: [YoutubeVideo] = [] 로 cell에 표시한 뒤 변경 예정입니다.

2023-09-07 06:07 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    func cellPrint() {
확인 후 수정했습니다.

2023-09-07 06:09 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +        textBoxStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -10).isActive = true
확인 후 수정했습니다.

2023-09-07 06:12 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +    //collectionView 속성
참고하겠습니다

2023-09-07 06:12 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        }
확인 후 수정했습니다.

2023-09-07 06:13 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
>          }
확인 후 수정했습니다.

2023-09-07 06:13 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        print(collectionView.bounds.width)
확인 후 수정했습니다.

2023-09-07 06:14 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        cell.uploadDateLabel.text = dateList[indexPath.row]
확인했습니다.
https://github.com/Publishable private(set) var videos: [YoutubeVideo] = [] 로 cell에 표시한 뒤 변경 예정입니다.

2023-09-08 04:54 UTC, rkrua approved these changes

2023-09-08 16:47 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeVideoCell.swift
> +    lazy var thumbnailImage: UIImageView = {
youtubeService 연결 후 수정했습니다.

2023-09-08 16:48 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +        cell.uploadDateLabel.text = dateList[indexPath.row]
```swift
let video = YoutubeService.shared.videos[indexPath.item]
cell.configure(video: video)
``` 
진용님의 도움을 받아 수정했습니다.

2023-09-08 16:49 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +    //home화면에 노출될 비디오 리스트 CollectionView
삭제했습니다.

2023-09-08 16:50 UTC, luttoli commented on YoutubeCloneApp/Views/HomeView/HomeView.swift
> +    let refreshControl = UIRefreshControl()
수정했습니다.

2023-09-09 23:47 UTC, merged